### ISSUE TITLE
Unrelated: How to deal with Silky images?

### ISSUE THREAD

**Issue by Gygarde** [TesterTesterov/MAPTool#1]
Hello!

Do you know how to edit AKB images from this engine? I have been looking around, but nothing works for me.

Thank you.

**Comment by Gygarde** [comment]
nvm, got it working.

**Comment by TesterTesterov** [comment]
Okay. You may want to see more data about technical work with the engine [in this article](https://anivisual.net/blog/2020-05-27-633).
